version: '3'
services:
  mongodb:
    container_name: mongodb
    restart: always
    image: "mongo:4"
    ports: ['27017:27017']
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 3MrYkWBBsc
  adminmongo:
    container_name: adminmongo
    depends_on:
        - 'mongodb'
    links:
      - 'mongodb'
    build:
      context: ./adminmongo
    restart: always
    ports:
      - "1234:1234"
    environment:
      - CONN_NAME=Alexandria
      - DB_HOST=mongodb
      - DB_USERNAME=root
      - DB_PASSWORD=3MrYkWBBsc